services:
  - type: web
    name: cosci-backend
    runtime: python3.9
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: HF_API_TOKEN
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1
    autoDeploy: true
